// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "directProvider": string;
      "apiAddress": string;
      "apiKey": string;
      "modelName": string;
      "requestTimeoutMs": string;
      "sidebarWidth": string;
    };
  }
}
