pref("extensions.zotero.zoteropaperreading.backendMode", "direct");
pref("extensions.zotero.zoteropaperreading.directProvider", "openai-compatible");
pref("extensions.zotero.zoteropaperreading.apiAddress", "https://api.openai.com/v1");
pref("extensions.zotero.zoteropaperreading.apiKey", "");
pref("extensions.zotero.zoteropaperreading.modelName", "gpt-4.1-mini");
pref("extensions.zotero.zoteropaperreading.companionUrl", "http://127.0.0.1:8765");
pref("extensions.zotero.zoteropaperreading.promptLanguage", "zh-CN");
pref("extensions.zotero.zoteropaperreading.requestTimeoutMs", "120000");
pref("extensions.zotero.zoteropaperreading.sidebarWidth", "420");
